import { Product, Order } from "@/types"

export const mockProducts: Product[] = [
  {
    id: "rec1",
    name: "Ethereal Gold Chain Necklace",
    slug: "ethereal-gold-chain-necklace",
    description: "A delicate gold-tone chain necklace that catches the light with every movement. Handcrafted by master artisans, this piece embodies the quiet luxury of minimal design. Perfect for layering or wearing alone as a statement of understated elegance.",
    price: 28500,
    originalPrice: 32000,
    images: [
      "/images/product-1.jpg",
    ],
    category: "Necklaces",
    subcategory: "Chains",
    tags: ["gold", "minimal", "layering", "daily-wear"],
    inStock: true,
    stockCount: 12,
    material: "Gold-tone finish",
    weight: "4.2g",
    dimensions: "Length: 18 inches",
    featured: true,
    newArrival: false,
    bestseller: true,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "rec2",
    name: "Luna Pearl Drop Earrings",
    slug: "luna-pearl-drop-earrings",
    description: "Freshwater pearls suspended from gold-tone hooks, creating a luminous drop that frames the face beautifully. Each pearl is hand-selected for its lustre and shape, making every pair subtly unique.",
    price: 18500,
    images: [
      "/images/product-2.jpg",
    ],
    category: "Earrings",
    subcategory: "Drops",
    tags: ["pearl", "gold", "elegant", "evening"],
    inStock: true,
    stockCount: 8,
    material: "Gold-tone finish, shell pearl",
    weight: "3.1g",
    dimensions: "Drop: 2.5cm",
    featured: true,
    newArrival: true,
    bestseller: false,
    createdAt: "2024-02-20T10:00:00Z",
  },
  {
    id: "rec3",
    name: "Solitaire Diamond Ring",
    slug: "solitaire-diamond-ring",
    description: "A single brilliant-cut cubic zirconia set in a sleek rhodium-finish band. The minimal bezel setting allows the stone to command full attention — a timeless symbol of commitment and refined taste.",
    price: 45000,
    originalPrice: 52000,
    images: [
      "/images/product-3.jpg",
    ],
    category: "Rings",
    subcategory: "Solitaire",
    tags: ["diamond", "white-gold", "engagement", "statement"],
    inStock: true,
    stockCount: 5,
    material: "Rhodium finish, cubic zirconia",
    weight: "2.8g",
    dimensions: "Stone: 0.5ct",
    featured: true,
    newArrival: false,
    bestseller: true,
    createdAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "rec4",
    name: "Heritage Kundan Bangle Set",
    slug: "heritage-kundan-bangle-set",
    description: "A set of four hand-enamelled bangles featuring traditional Kundan work with Kundan stones set in a gold-tone finish. The vibrant Meenakari enamel work on the inner surface adds a hidden burst of colour.",
    price: 67500,
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800&q=80",
      "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=800&q=80",
    ],
    category: "Bangles",
    subcategory: "Kundan",
    tags: ["kundan", "diamond", "traditional", "wedding"],
    inStock: true,
    stockCount: 3,
    material: "Gold-tone finish, Kundan stones, Meenakari enamel",
    weight: "45g (set of 4)",
    dimensions: "Size: 2.6",
    featured: false,
    newArrival: false,
    bestseller: true,
    createdAt: "2024-01-05T10:00:00Z",
  },
  {
    id: "rec5",
    name: "Minimalist Bar Bracelet",
    slug: "minimalist-bar-bracelet",
    description: "A sleek horizontal gold bar on a fine chain bracelet. The clean geometry and polished finish make this an everyday essential that transitions seamlessly from boardroom to dinner.",
    price: 12500,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80",
      "https://images.unsplash.com/photo-1599643478518-17488fbbcd75?w=800&q=80",
    ],
    category: "Bracelets",
    subcategory: "Chains",
    tags: ["gold", "minimal", "daily-wear", "modern"],
    inStock: true,
    stockCount: 15,
    material: "Gold-tone finish",
    weight: "2.1g",
    dimensions: "Length: 7 inches, Bar: 2cm",
    featured: false,
    newArrival: true,
    bestseller: false,
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "rec6",
    name: "Emerald Lotus Pendant",
    slug: "emerald-lotus-pendant",
    description: "A lotus-inspired pendant featuring a emerald-green stone at its centre, surrounded by pavé stones in a gold-tone finish. The lotus symbolises purity and spiritual awakening in Indian tradition.",
    price: 38500,
    originalPrice: 42000,
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80",
    ],
    category: "Necklaces",
    subcategory: "Pendants",
    tags: ["emerald", "diamond", "gold", "spiritual"],
    inStock: true,
    stockCount: 6,
    material: "Gold-tone finish, emerald-green & clear stones",
    weight: "5.4g",
    dimensions: "Pendant: 2cm x 2cm",
    featured: false,
    newArrival: true,
    bestseller: false,
    createdAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "rec7",
    name: "Rose Gold Hoop Earrings",
    slug: "rose-gold-hoop-earrings",
    description: "Classic hoop earrings in a warm rose gold-tone finish with a satin-brushed finish. The medium size makes them versatile enough for both casual and formal occasions.",
    price: 22000,
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&q=80",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
    ],
    category: "Earrings",
    subcategory: "Hoops",
    tags: ["rose-gold", "hoops", "daily-wear", "classic"],
    inStock: true,
    stockCount: 10,
    material: "Rose gold-tone finish",
    weight: "3.8g",
    dimensions: "Diameter: 2.5cm",
    featured: false,
    newArrival: false,
    bestseller: true,
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "rec8",
    name: "Temple Jewellery Choker",
    slug: "temple-jewellery-choker",
    description: "An ornate choker necklace inspired by South Indian temple architecture, featuring intricate filigree work in a gold-tone finish with ruby and pearl accents. A statement piece for weddings and festive occasions.",
    price: 95000,
    images: [
      "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=800&q=80",
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800&q=80",
    ],
    category: "Necklaces",
    subcategory: "Chokers",
    tags: ["temple", "gold", "ruby", "pearl", "wedding"],
    inStock: true,
    stockCount: 2,
    material: "Gold-tone finish, ruby-red stones, shell pearls",
    weight: "68g",
    dimensions: "Length: 14 inches",
    featured: false,
    newArrival: false,
    bestseller: false,
    createdAt: "2024-01-08T10:00:00Z",
  },
  {
    id: "rec9",
    name: "Sapphire Stud Earrings",
    slug: "sapphire-stud-earrings",
    description: "Round-cut blue stones set in a rhodium finish with a clear-stone halo. The deep blue hue is reminiscent of the Indian monsoon sky — rich, mysterious, and captivating.",
    price: 32000,
    originalPrice: 36000,
    images: [
      "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&q=80",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80",
    ],
    category: "Earrings",
    subcategory: "Studs",
    tags: ["sapphire", "white-gold", "diamond", "elegant"],
    inStock: true,
    stockCount: 7,
    material: "Rhodium finish, blue & clear stones",
    weight: "2.4g",
    dimensions: "Stone: 0.8ct each",
    featured: false,
    newArrival: true,
    bestseller: false,
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "rec10",
    name: "Antique Gold Jhumka",
    slug: "antique-gold-jhumka",
    description: "Traditional bell-shaped jhumka earrings with an antique gold finish, featuring intricate temple motifs and pearl drops. The oxidised detailing adds vintage character to this heritage design.",
    price: 28000,
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&q=80",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
    ],
    category: "Earrings",
    subcategory: "Jhumkas",
    tags: ["antique", "gold", "pearl", "traditional", "wedding"],
    inStock: true,
    stockCount: 4,
    material: "Gold-tone finish, shell pearls",
    weight: "8.5g (pair)",
    dimensions: "Length: 4cm",
    featured: false,
    newArrival: false,
    bestseller: true,
    createdAt: "2024-01-12T10:00:00Z",
  },
  {
    id: "rec11",
    name: "Diamond Tennis Bracelet",
    slug: "diamond-tennis-bracelet",
    description: "A continuous line of brilliant-cut cubic zirconia set in a rhodium finish. The classic tennis bracelet design offers timeless elegance and catches light from every angle.",
    price: 125000,
    images: [
      "/images/product-4.jpg",
    ],
    category: "Bracelets",
    subcategory: "Tennis",
    tags: ["diamond", "white-gold", "luxury", "statement"],
    inStock: true,
    stockCount: 2,
    material: "Rhodium finish, cubic zirconia",
    weight: "12g",
    dimensions: "Length: 7 inches, 3ct total diamond weight",
    featured: true,
    newArrival: false,
    bestseller: false,
    createdAt: "2024-01-25T10:00:00Z",
  },
  {
    id: "rec12",
    name: "Mangalsutra Modern",
    slug: "mangalsutra-modern",
    description: "A contemporary reinterpretation of the traditional mangalsutra, featuring a single black bead strand with a minimal gold pendant. Designed for the modern woman who honours tradition with subtlety.",
    price: 15500,
    images: [
      "https://images.unsplash.com/photo-1599643478518-17488fbbcd75?w=800&q=80",
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80",
    ],
    category: "Necklaces",
    subcategory: "Mangalsutra",
    tags: ["gold", "traditional", "modern", "daily-wear"],
    inStock: true,
    stockCount: 9,
    material: "Gold-tone finish, black beads",
    weight: "3.5g",
    dimensions: "Length: 20 inches",
    featured: false,
    newArrival: true,
    bestseller: false,
    createdAt: "2024-03-20T10:00:00Z",
  },
]

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    userId: "user1",
    items: [
      { product: mockProducts[0], quantity: 1 },
      { product: mockProducts[2], quantity: 1 },
    ],
    total: 73500,
    status: "delivered",
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "ORD-002",
    userId: "user1",
    items: [
      { product: mockProducts[1], quantity: 2 },
    ],
    total: 37000,
    status: "shipped",
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "ORD-003",
    userId: "user2",
    items: [
      { product: mockProducts[3], quantity: 1 },
      { product: mockProducts[6], quantity: 1 },
    ],
    total: 89500,
    status: "confirmed",
    createdAt: "2024-03-20T10:00:00Z",
  },
  {
    id: "ORD-004",
    userId: "user3",
    items: [
      { product: mockProducts[10], quantity: 1 },
    ],
    total: 125000,
    status: "pending",
    createdAt: "2024-03-22T10:00:00Z",
  },
  {
    id: "ORD-005",
    userId: "user1",
    items: [
      { product: mockProducts[4], quantity: 1 },
      { product: mockProducts[5], quantity: 1 },
    ],
    total: 51000,
    status: "delivered",
    createdAt: "2024-02-10T10:00:00Z",
  },
]
